### ISSUE TITLE
Component 동적 생성

### ISSUE THREAD

**Issue by HyunBaeJung** [hyper-web-space/live-chat-client#11]
## 개발 방향

모든 채팅방과 동시에 통신 할 수 있도록
로그인과 동시에 참여 중인 모든 채팅방의 컴포넌트 생성
Recoil 사용해 관리하며 페이지 전환 개발

**Comment by HyunBaeJung** [comment]
### To-Do

- [x] chat room Mock Up 제작
- [x] Recoil로 채팅방 리스트 관리 객체 생성
- [x] chat room 상태 관리 function 작성
- [x] 화면 전환 설계 (App.tsx)
